# Generated by Django 2.0.13 on 2019-02-26 01:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_snow', '0002_changemgmt_add_createtime_closetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeOrder',
            fields=[
                ('sys_id', models.UUIDField(primary_key=True, serialize=False)),
                ('number', models.CharField(help_text='The Change Order number', max_length=32)),
                ('title', models.CharField(help_text='Title of the ServiceNow Change Order', max_length=160)),
                ('description', models.TextField(help_text='Description of the ServiceNow Change Order', validators=[django.core.validators.MaxLengthValidator(4000)])),
                ('assignment_group_guid', models.UUIDField()),
                ('state', models.CharField(choices=[('1', 'Open'), ('2', 'In Progress'), ('3', 'Complete'), ('4', 'Complete With Errors')], help_text='The current state the change order is in.', max_length=3)),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the Change Order was created')),
                ('closed_time', models.DateTimeField(help_text='Timestamp when the Change Order was closed', null=True)),
            ],
            options={
                'verbose_name': 'service-now change order',
                'verbose_name_plural': 'service-now change orders',
            },
        ),
        migrations.DeleteModel(
            name='ChangeRequest',
        ),
    ]
